(**** Beginning of end.gcode ****)
(**** begin move to cooling position ****)
G1 X0.0 Y55.0 F3300.0 (move to cooling position)
(**** end move to cooling position ****)
(**** begin filament reversal ****)
M108 R50 T0
M102 T0 (Extruder on, reverse)
G04 P100 (Wait t/1000 seconds)
M103 T0 (Extruder off)
(**** end filament reversal ****)
M18 (Turn off steppers)
(**** begin cool to avoid thermal soak in next print ****)
M109 S0 T0 (set heated-build-platform temperature)
M106      (turn extruder fan on)
M109 S100 (set extruder temp)
M6 T0     (wait for cooling)
M107      (turn extruder fan off)
(**** end cool to avoid thermal soak in next print ****)
(**** begin cool for safety ****)
M104 S0 (set extruder temperature)
M109 S0 (set heated-build-platform temperature)
(**** end cool for safety ****)
(**** end of end.gcode ****)